
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Victor1
 */
public class archivos extends javax.swing.JFrame {

    /**
     * Creates new form archivos
     */
    public archivos() {
        initComponents();
        // Personalización de ventana
        personalizacion_ventana();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archivos_panel = new javax.swing.JPanel();
        archivos_titulo = new javax.swing.JLabel();
        username_11 = new javax.swing.JLabel();
        username_23 = new javax.swing.JLabel();
        username_22 = new javax.swing.JLabel();
        username_12 = new javax.swing.JLabel();
        username_13 = new javax.swing.JLabel();
        username_21 = new javax.swing.JLabel();
        folder_1 = new javax.swing.JButton();
        folder_2 = new javax.swing.JButton();
        folder_3 = new javax.swing.JButton();
        folder_6 = new javax.swing.JButton();
        folder_5 = new javax.swing.JButton();
        folder_4 = new javax.swing.JButton();
        inicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        archivos_panel.setBackground(new java.awt.Color(215, 227, 252));

        archivos_titulo.setBackground(new java.awt.Color(0, 0, 0));
        archivos_titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        archivos_titulo.setForeground(new java.awt.Color(0, 0, 102));
        archivos_titulo.setText("Archivos");

        username_11.setBackground(new java.awt.Color(215, 227, 252));
        username_11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        username_11.setForeground(new java.awt.Color(0, 0, 153));
        username_11.setText("username_11");

        username_23.setBackground(new java.awt.Color(215, 227, 252));
        username_23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        username_23.setForeground(new java.awt.Color(0, 0, 153));
        username_23.setText("username_23");

        username_22.setBackground(new java.awt.Color(215, 227, 252));
        username_22.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        username_22.setForeground(new java.awt.Color(0, 0, 153));
        username_22.setText("username_22");

        username_12.setBackground(new java.awt.Color(215, 227, 252));
        username_12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        username_12.setForeground(new java.awt.Color(0, 0, 153));
        username_12.setText("username_12");

        username_13.setBackground(new java.awt.Color(215, 227, 252));
        username_13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        username_13.setForeground(new java.awt.Color(0, 0, 153));
        username_13.setText("username_13");

        username_21.setBackground(new java.awt.Color(215, 227, 252));
        username_21.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        username_21.setForeground(new java.awt.Color(0, 0, 153));
        username_21.setText("username_21");

        folder_1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        folder_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        folder_2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        folder_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        folder_3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        folder_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        folder_6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        folder_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        folder_5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        folder_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        folder_4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 10)); // NOI18N
        folder_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        inicio.setBackground(new java.awt.Color(118, 158, 219));
        inicio.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        inicio.setForeground(new java.awt.Color(0, 0, 153));
        inicio.setText("Inicio");
        inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout archivos_panelLayout = new javax.swing.GroupLayout(archivos_panel);
        archivos_panel.setLayout(archivos_panelLayout);
        archivos_panelLayout.setHorizontalGroup(
            archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, archivos_panelLayout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(username_21)
                .addGap(459, 459, 459))
            .addGroup(archivos_panelLayout.createSequentialGroup()
                .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivos_panelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(archivos_panelLayout.createSequentialGroup()
                                .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(folder_1)
                                    .addComponent(username_11))
                                .addGap(84, 84, 84)
                                .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(archivos_titulo)
                                    .addGroup(archivos_panelLayout.createSequentialGroup()
                                        .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(username_12)
                                            .addComponent(username_22)
                                            .addComponent(folder_2)
                                            .addComponent(folder_5))
                                        .addGap(99, 99, 99)
                                        .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(folder_3)
                                            .addComponent(username_23)
                                            .addComponent(username_13)
                                            .addComponent(folder_6, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(archivos_panelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(folder_4))))
                    .addGroup(archivos_panelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        archivos_panelLayout.setVerticalGroup(
            archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivos_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(archivos_titulo)
                .addGap(55, 55, 55)
                .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivos_panelLayout.createSequentialGroup()
                        .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(folder_2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(folder_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(91, 91, 91)
                        .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username_12)
                            .addComponent(username_11)
                            .addComponent(username_13)))
                    .addComponent(folder_3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(archivos_panelLayout.createSequentialGroup()
                        .addComponent(folder_5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(folder_4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(folder_6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(archivos_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username_21)
                    .addComponent(username_22)
                    .addComponent(username_23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(inicio)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(archivos_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(archivos_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicioActionPerformed
        this.dispose();
        menu panel_menu = new menu();
        panel_menu.setVisible(true);
    }//GEN-LAST:event_inicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel archivos_panel;
    public static javax.swing.JLabel archivos_titulo;
    private javax.swing.JButton folder_1;
    private javax.swing.JButton folder_2;
    private javax.swing.JButton folder_3;
    private javax.swing.JButton folder_4;
    private javax.swing.JButton folder_5;
    private javax.swing.JButton folder_6;
    private javax.swing.JButton inicio;
    private javax.swing.JLabel username_11;
    private javax.swing.JLabel username_12;
    private javax.swing.JLabel username_13;
    private javax.swing.JLabel username_21;
    private javax.swing.JLabel username_22;
    private javax.swing.JLabel username_23;
    // End of variables declaration//GEN-END:variables

    public void personalizacion_ventana(){
        // Posición, título e icono
        this.setLocationRelativeTo(null);
        this.setTitle("Archivos");
        ImageIcon img_2 = new ImageIcon("images/icon_perezoso_4.png");
        setIconImage(img_2.getImage());
        // Título, Usernames and folder buttons
        archivos_titulo.setBounds(280, 20, 100, 40);
        archivos_panel.add(archivos_titulo);
        folder_1.setBounds(120, 130, 100, 70);
        ImageIcon button = new ImageIcon("images/folder_button.png");
        folder_1.setIcon(new ImageIcon(button.getImage().getScaledInstance(folder_1.getWidth(), folder_1.getHeight(), Image.SCALE_SMOOTH)));
        archivos_panel.add(folder_1);
        username_11.setBounds(130, 210, 100, 20);
        archivos_panel.add(username_11);
        
        folder_2.setBounds(270, 130, 100, 70);
        folder_2.setIcon(new ImageIcon(button.getImage().getScaledInstance(folder_2.getWidth(), folder_2.getHeight(), Image.SCALE_SMOOTH)));
        archivos_panel.add(folder_2);
        username_12.setBounds(280, 210, 100, 20);
        archivos_panel.add(username_12);
        
        folder_3.setBounds(420, 130, 100, 70);
        folder_3.setIcon(new ImageIcon(button.getImage().getScaledInstance(folder_3.getWidth(), folder_2.getHeight(), Image.SCALE_SMOOTH)));
        archivos_panel.add(folder_3);
        username_13.setBounds(430, 210, 100, 20);
        archivos_panel.add(username_13);
        
        folder_4.setBounds(120, 270, 100, 70);
        folder_4.setIcon(new ImageIcon(button.getImage().getScaledInstance(folder_4.getWidth(), folder_2.getHeight(), Image.SCALE_SMOOTH)));
        archivos_panel.add(folder_4);
        username_21.setBounds(130, 350, 100, 20);
        archivos_panel.add(username_21);
        
        folder_5.setBounds(270, 270, 100, 70);
        folder_5.setIcon(new ImageIcon(button.getImage().getScaledInstance(folder_5.getWidth(), folder_2.getHeight(), Image.SCALE_SMOOTH)));
        archivos_panel.add(folder_5);
        username_22.setBounds(280, 350, 100, 20);
        archivos_panel.add(username_22);
        
        folder_6.setBounds(420, 270, 100, 70);
        folder_6.setIcon(new ImageIcon(button.getImage().getScaledInstance(folder_6.getWidth(), folder_2.getHeight(), Image.SCALE_SMOOTH)));
        archivos_panel.add(folder_6);
        username_23.setBounds(430, 350, 100, 20);
        archivos_panel.add(username_23);
        
        inicio.setBounds(20, 440, 70, 30);
        archivos_panel.add(inicio);
    }
}
